/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as PerfilRouteImport } from './routes/perfil'
import { Route as MisEventosRouteImport } from './routes/mis-eventos'
import { Route as LoginRouteImport } from './routes/login'
import { Route as GuardadosRouteImport } from './routes/guardados'
import { Route as ExplorarRouteImport } from './routes/explorar'
import { Route as CrearRouteImport } from './routes/crear'
import { Route as ContactoRouteImport } from './routes/contacto'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EventoIdRouteImport } from './routes/evento.$id'
import { Route as EditarIdRouteImport } from './routes/editar.$id'
import { Route as CategoriaSlugRouteImport } from './routes/categoria.$slug'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const PerfilRoute = PerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => rootRouteImport,
} as any)
const MisEventosRoute = MisEventosRouteImport.update({
  id: '/mis-eventos',
  path: '/mis-eventos',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const GuardadosRoute = GuardadosRouteImport.update({
  id: '/guardados',
  path: '/guardados',
  getParentRoute: () => rootRouteImport,
} as any)
const ExplorarRoute = ExplorarRouteImport.update({
  id: '/explorar',
  path: '/explorar',
  getParentRoute: () => rootRouteImport,
} as any)
const CrearRoute = CrearRouteImport.update({
  id: '/crear',
  path: '/crear',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactoRoute = ContactoRouteImport.update({
  id: '/contacto',
  path: '/contacto',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EventoIdRoute = EventoIdRouteImport.update({
  id: '/evento/$id',
  path: '/evento/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const EditarIdRoute = EditarIdRouteImport.update({
  id: '/editar/$id',
  path: '/editar/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriaSlugRoute = CategoriaSlugRouteImport.update({
  id: '/categoria/$slug',
  path: '/categoria/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/contacto': typeof ContactoRoute
  '/crear': typeof CrearRoute
  '/explorar': typeof ExplorarRoute
  '/guardados': typeof GuardadosRoute
  '/login': typeof LoginRoute
  '/mis-eventos': typeof MisEventosRoute
  '/perfil': typeof PerfilRoute
  '/register': typeof RegisterRoute
  '/categoria/$slug': typeof CategoriaSlugRoute
  '/editar/$id': typeof EditarIdRoute
  '/evento/$id': typeof EventoIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/contacto': typeof ContactoRoute
  '/crear': typeof CrearRoute
  '/explorar': typeof ExplorarRoute
  '/guardados': typeof GuardadosRoute
  '/login': typeof LoginRoute
  '/mis-eventos': typeof MisEventosRoute
  '/perfil': typeof PerfilRoute
  '/register': typeof RegisterRoute
  '/categoria/$slug': typeof CategoriaSlugRoute
  '/editar/$id': typeof EditarIdRoute
  '/evento/$id': typeof EventoIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/contacto': typeof ContactoRoute
  '/crear': typeof CrearRoute
  '/explorar': typeof ExplorarRoute
  '/guardados': typeof GuardadosRoute
  '/login': typeof LoginRoute
  '/mis-eventos': typeof MisEventosRoute
  '/perfil': typeof PerfilRoute
  '/register': typeof RegisterRoute
  '/categoria/$slug': typeof CategoriaSlugRoute
  '/editar/$id': typeof EditarIdRoute
  '/evento/$id': typeof EventoIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/contacto'
    | '/crear'
    | '/explorar'
    | '/guardados'
    | '/login'
    | '/mis-eventos'
    | '/perfil'
    | '/register'
    | '/categoria/$slug'
    | '/editar/$id'
    | '/evento/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/contacto'
    | '/crear'
    | '/explorar'
    | '/guardados'
    | '/login'
    | '/mis-eventos'
    | '/perfil'
    | '/register'
    | '/categoria/$slug'
    | '/editar/$id'
    | '/evento/$id'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/contacto'
    | '/crear'
    | '/explorar'
    | '/guardados'
    | '/login'
    | '/mis-eventos'
    | '/perfil'
    | '/register'
    | '/categoria/$slug'
    | '/editar/$id'
    | '/evento/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  ContactoRoute: typeof ContactoRoute
  CrearRoute: typeof CrearRoute
  ExplorarRoute: typeof ExplorarRoute
  GuardadosRoute: typeof GuardadosRoute
  LoginRoute: typeof LoginRoute
  MisEventosRoute: typeof MisEventosRoute
  PerfilRoute: typeof PerfilRoute
  RegisterRoute: typeof RegisterRoute
  CategoriaSlugRoute: typeof CategoriaSlugRoute
  EditarIdRoute: typeof EditarIdRoute
  EventoIdRoute: typeof EventoIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/perfil': {
      id: '/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof PerfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mis-eventos': {
      id: '/mis-eventos'
      path: '/mis-eventos'
      fullPath: '/mis-eventos'
      preLoaderRoute: typeof MisEventosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guardados': {
      id: '/guardados'
      path: '/guardados'
      fullPath: '/guardados'
      preLoaderRoute: typeof GuardadosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explorar': {
      id: '/explorar'
      path: '/explorar'
      fullPath: '/explorar'
      preLoaderRoute: typeof ExplorarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crear': {
      id: '/crear'
      path: '/crear'
      fullPath: '/crear'
      preLoaderRoute: typeof CrearRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contacto': {
      id: '/contacto'
      path: '/contacto'
      fullPath: '/contacto'
      preLoaderRoute: typeof ContactoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/evento/$id': {
      id: '/evento/$id'
      path: '/evento/$id'
      fullPath: '/evento/$id'
      preLoaderRoute: typeof EventoIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/editar/$id': {
      id: '/editar/$id'
      path: '/editar/$id'
      fullPath: '/editar/$id'
      preLoaderRoute: typeof EditarIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categoria/$slug': {
      id: '/categoria/$slug'
      path: '/categoria/$slug'
      fullPath: '/categoria/$slug'
      preLoaderRoute: typeof CategoriaSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  ContactoRoute: ContactoRoute,
  CrearRoute: CrearRoute,
  ExplorarRoute: ExplorarRoute,
  GuardadosRoute: GuardadosRoute,
  LoginRoute: LoginRoute,
  MisEventosRoute: MisEventosRoute,
  PerfilRoute: PerfilRoute,
  RegisterRoute: RegisterRoute,
  CategoriaSlugRoute: CategoriaSlugRoute,
  EditarIdRoute: EditarIdRoute,
  EventoIdRoute: EventoIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
